SELECT
    sales.CODE,
    PVP,
    MANTENIMIENTO_GRATUITO,
    SEGURO_BATERIA_LARGO_PLAZO,
    MANTENIMIENTO_GRATUITO,
    FIN_GARANTIA,
    COSTE_VENTA_NO_IMPUESTOS,
    IMPUESTOS,
    EXTENSION_GARANTIA,
    EN_GARANTIA
    
FROM    
    [DATAEX].[001_sales] AS sales